# Generated by Django 5.1.15 on 2026-04-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0003_add_instagram_personal_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastodonappregistration',
            name='instance_url',
            field=models.URLField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='instance_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
