# Generated by Django 5.1.15 on 2026-04-16 05:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('composer', '0015_per_account_status'),
        ('social_accounts', '0004_alter_mastodonappregistration_instance_url_and_more'),
        ('workspaces', '0002_replace_icon_url_with_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMetricsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('profile_views', models.IntegerField(blank=True, null=True)),
                ('website_clicks', models.IntegerField(blank=True, null=True)),
                ('snapshot_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_snapshots', to='social_accounts.socialaccount')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_metrics_snapshots', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-snapshot_at'],
                'indexes': [models.Index(fields=['social_account', 'snapshot_at'], name='analytics_a_social__0dedd1_idx'), models.Index(fields=['workspace', 'snapshot_at'], name='analytics_a_workspa_9d4aab_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.IntegerField(default=0, help_text='Number of times the post was viewed')),
                ('reach', models.IntegerField(default=0, help_text='Number of unique people who saw it')),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0, help_text='Bookmarks, retweets, etc.')),
                ('clicks', models.IntegerField(default=0, help_text='Clicks on links')),
                ('video_views', models.IntegerField(blank=True, help_text='For video posts only', null=True)),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage (0-100)', max_digits=5)),
                ('snapshot_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('platform_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='composer.platformpost')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-snapshot_at'],
                'indexes': [models.Index(fields=['platform_post', 'snapshot_at'], name='analytics_a_platfor_838e41_idx'), models.Index(fields=['workspace', 'snapshot_at'], name='analytics_a_workspa_a1e14f_idx')],
            },
        ),
    ]
